### ISSUE TITLE
更新版本用的version是如何生成出来的

### ISSUE THREAD

**Issue by 1978mountain** [DrFlower/TowerDefense-GameFramework-Demo#1]
查看代码会加载一个builderinfo.txt文件，配置了CheckVersionUrl，但是不知道{0}Version.txt这个文件是如何生成出来的。

**Comment by DrFlower** [comment]
hi，这个文件其实是我手填的，数据在打完AB包后的BuildReport/(版本号)/BuildLog.txt文件里，文本最下方有大小数据。当然也可以做成自动化，在菜单GameFramework/Resource Tools/Reources Builder打开GF的资源构建面板，设置自己的回调到BuildEventHandler即可，这个回调会在构建资源时被调用，并传入相关参数，自己编写根据参数生成文件的逻辑即可，回调应该是对应IBuildEventHandler.cs里的OnPreprocessAllPlatforms方法。

**Comment by 1978mountain** [comment]
ok，明白了
