### ISSUE TITLE
生成DefaultConfig的工具有误

### ISSUE THREAD

**Issue by shi-yh** [DrFlower/TowerDefense-GameFramework-Demo#3]
似乎没有重写Config相关的生成逻辑？
其实我也不太理解原作者把datatable和config分开的用意

**Comment by DrFlower** [comment]
emmmm，Tools/Generate Config这个菜单工具确实会报错，由于时间太久远我不太能理清这段生成代码的缘由了。。DefaultConfig是不需要生成二进制文件的，直接修改源文件DefaultConfig.txt即可生效，似乎不需要什么生成逻辑，我决定先把Tools/Generate Config这个菜单工具屏蔽了。

至于DataTable和Config分开，就代码提供的功能上看：

DataTable完全是一个静态配置，它只能解析配置文件，然后通过接口获取解析出来的数据，运行时是不能往datatable添加数据的，这个是完全对应平常开发中与策划直接对接的配置表。

而Config则有运行时添加、删除数据的接口，与其说他是读取文件配置，倒不如理解为，他首先是个运行时可以添加、删除配置的模块，然后再在这基础上添加了可以从文件中读取配置的功能，相当于是个运行时可以运行时增删查改的全局配置，有点像Setting，而又有点不同就是运行时修改的内容不会储存到硬盘上。
