### ISSUE TITLE
请问您的这个项目如果发布webgl

### ISSUE THREAD

**Issue by laoyuan1992** [DrFlower/TowerDefense-GameFramework-Demo#4]
因为项目需要，要学习gf和发布webgl。请问你的这个demo可以出一个发布webgl的教程嘛

**Comment by DrFlower** [comment]
这个demo除了bug反馈，应该不会再更新了，知乎上的源码解析系列文章后续有时间会更新资源篇，用gf发布webgl我自己也没踩坑过。。或许在群里可以多咨询咨询？我看很多人都碰到webgl的问题，或许有能提供帮助的
